build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
    - "ffmpeg"
  python_packages:
    - "accelerate==0.28.0"
    - "diffusers==0.27.0"
    - "transformers==4.38.2"
    - "peft==0.9.0"
